[package]
name = "planets_simulator"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.24.0"
convexhull3d = "0.5.0"
env_logger = "0.11.8"
glam = "0.30.9"
nalgebra = "0.34.1"
pollster = "0.4.0"
wgpu = "27.0.1"
winit = "0.30.12"
